# Name of workflow
name: Lint and Test
# When workflow is triggered
on:
    push:
        branches:
            - main
    pull_request:
        types: ['opened', 'synchronize']
        branches:
            - main
# Jobs to carry out
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        env:
            CI: true
        steps:
            # Get code from repo
            - name: Checkout code
              uses: actions/checkout@v2
            # Install NodeJS
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            # Run npm install
            - name: Install dependencies
              run: npm ci
            # Run lint
            - name: Run lint
              run: npm run lint
            # Run unit tests
            - name: Run tests
              run: npm run test:ci
